basePath: /hello
info:
  title: hello
  version: 1.0.0
  x-ibm-name: hello
paths:
  /:
    delete:
      consumes: []
      produces: []
      responses:
        '200':
          description: success
          schema:
            type: string
    get:
      consumes: []
      produces: []
      responses:
        '200':
          description: success
          schema:
            type: string
    head:
      consumes: []
      produces: []
      responses:
        '200':
          description: success
          schema:
            type: string
    patch:
      consumes: []
      produces: []
      responses:
        '200':
          description: success
          schema:
            type: string
    post:
      consumes: []
      produces: []
      responses:
        '200':
          description: success
          schema:
            type: string
    put:
      consumes: []
      produces: []
      responses:
        '200':
          description: success
          schema:
            type: string
schemes:
  - https
security:
  - clientID: []
securityDefinitions:
  clientID:
    in: header
    name: X-IBM-Client-Id
    type: apiKey
swagger: '2.0'
x-ibm-configuration:
  assembly:
    execute:
      - gatewayscript:
          version: 2.0.0
          title: gatewayscript
  cors:
    enabled: true
  enforced: true
  gateway: datapower-api-gateway
  phase: realized
  properties:
    target-url:
      description: The URL of the target service
      encoded: false
      value: http://example.com/operation-name
  testable: true
  type: rest
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
